# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e26889f208dce266b32c4dd9de2c9373b23b212535d63c77fd0e26951ea06227e4eb447903883ec50ab402b342c6b13a7b49c625daf97cd3d4a817b835825560

test:
  secret_key_base: 159a99d051284523d68d487e85a7bf7b863326c4086e3bb0e64c7735a37ee927bf0716fd654f5b525d34d03b404ee91edf9bdf44845e795ca643620ba18eb43c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
